$ANSIBLE_VAULT;1.1;AES256
61323237346564663232643663383438366139306666306633643664373565303936303736353033
3839666338326362663130623461333135306530396264390a323464386133373235316162393432
30313535623465653463313034346137323361626531323939323337313262366134313363396234
3036633335343537350a623164656132623065303530346364366534326262613039396638393132
34313533346261633563343730363837336564343865333737653532313231633939323836326165
66633233633532396362656663383266363935323033313265316365313465333261346464626130
63343164336431306161386164396563633239333161313831333961336439323764303930663864
64626439386438323335383534376239383938646461376564353035646334373639663261623965
64316637646430626166393466616635386130643531316239343366313036363632313632633336
33366331326332353730613033373930336235323365303061613563663739313164643566373238
65303165626533613537386134336634623161393336633462303730363562623130306131393439
31346664353037316434626365363863646363366265316464356235366434303134613834356665
6334
